package ru.demo.tests.api.objects;

import io.qameta.allure.Owner;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import io.restassured.response.Response;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Tags;
import org.junit.jupiter.api.Test;
import ru.demo.models.dictData.DictData400ResponseModel;
import ru.demo.models.dictData.DictData404ResponseModel;
import ru.demo.models.dictData.DictData409ResponseModel;
import ru.demo.models.objects.*;
import ru.demo.tests.api.BaseApi;
import ru.demo.data.randomData.RandomData;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertAll;

@DisplayName("Create object API tests")
public class CreateObjectDictTests extends BaseApi {
    private RandomData randomValues = new RandomData();

    @Test
    @DisplayName("Create a new object with auto-generated code")
    @Tags({@Tag("smoke"), @Tag("regress")})
    @Severity(SeverityLevel.CRITICAL)
    @Owner("Yulia Azovtseva")
    void createObjectWithAutoGeneratedCodeTest() {
        CreateObjectRequestModel randomDataObject = randomValues.allRequiredParams();
        Response response = objectsApi.createObject(randomDataObject);
        CreateObjectResponseModel responseObject = response.as(CreateObjectResponseModel.class);

        assertAll(
                () -> assertThat(response.getStatusCode()).isEqualTo(200),
                () -> assertThat(responseObject.getCode()).isNotNull(),
                () -> assertThat(responseObject.getAddress()).isEqualTo(randomDataObject.getAddress()),
                () -> assertThat(responseObject.getParentCode()).isEqualTo(randomDataObject.getParentCode())
        );
        objectsApi.deleteObject(responseObject.getCode());
    }

    @Test
    @DisplayName("Create a new object with user-defined code")
    @Tag("regress")
    @Severity(SeverityLevel.NORMAL)
    @Owner("Yulia Azovtseva")
    void createObjectWithUserDefinedCodeTest() {
        CreateObjectRequestModel randomDataObject = randomValues.allRequiredParamsWithCode(randomValues.generateRandomObjectCode());
        Response response = objectsApi.createObject(randomDataObject);
        CreateObjectResponseModel responseObject = response.as(CreateObjectResponseModel.class);

        assertAll(
                () -> assertThat(response.getStatusCode()).isEqualTo(200),
                () -> assertThat(responseObject.getAddress()).isEqualTo(responseObject.getAddress()),
                () -> assertThat(responseObject.getParentCode()).isEqualTo(responseObject.getParentCode()),
                () -> assertThat(responseObject.getCode()).isEqualTo(responseObject.getCode())
        );
        objectsApi.deleteObject(responseObject.getCode());
    }

    @Test
    @DisplayName("Attempt to create an object with existing code")
    @Tag("regress")
    @Severity(SeverityLevel.NORMAL)
    @Owner("Yulia Azovtseva")
    void createObjectWithExistingCodeTest() {
        String code = randomValues.generateRandomObjectCode();

        CreateObjectRequestModel randomDataObject = randomValues.allRequiredParamsWithCode(code);
        objectsApi.createObject(randomDataObject);

        CreateObjectRequestModel randomDataObjectNew = randomValues.allRequiredParamsWithCode(code);
        Response response = objectsApi.createObject(randomDataObjectNew);
        DictData409ResponseModel responseObject = response.as(DictData409ResponseModel.class);

        assertAll(
                () -> assertThat(response.getStatusCode()).isEqualTo(409),
                () -> assertThat(responseObject.getErrorCode()).isEqualTo("DuplicateObjectError"),
                () -> assertThat(responseObject.getErrorData().getObjectType()).isEqualTo("obj")
        );
        objectsApi.deleteObject(code);
    }

    @Test
    @DisplayName("Attempt to create an object with missing 'name' parameter")
    @Tag("regress")
    @Severity(SeverityLevel.NORMAL)
    @Owner("Yulia Azovtseva")
    void createObjectWithMissingNameParamTest() {
        CreateObjectRequestModel randomDataObject = CreateObjectRequestModel.builder()
                .objType(randomValues.getRandomObjectType().getObjectTypeCode())
                .address(randomValues.generateRandomAddress())
                .parentCode(randomValues.getRandomDistrict().getCode())
                .build();
        Response response = objectsApi.createObject(randomDataObject);
        DictData400ResponseModel responseObject = response.as(DictData400ResponseModel.class);

        assertAll(
                () -> assertThat(response.getStatusCode()).isEqualTo(400),
                () -> assertThat(responseObject.getErrorCode()).isEqualTo("IllegalParameterError"),
                () -> assertThat(responseObject.getErrorData().getParam()).isEqualTo("name")
        );
    }

    @Test
    @DisplayName("Attempt to create an object with invalid 'parentCode' parameter")
    @Tag("regress")
    @Severity(SeverityLevel.NORMAL)
    @Owner("Yulia Azovtseva")
    void createObjectWithInvalidParentParamTest() {
        String invalidParentCode = "9999";
        CreateObjectRequestModel randomDataObject = CreateObjectRequestModel.builder()
                .objType(randomValues.getRandomObjectType().getObjectTypeCode())
                .address(randomValues.generateRandomAddress())
                .parentCode(invalidParentCode)
                .name("Object Name")
                .build();
        Response response = objectsApi.createObject(randomDataObject);
        DictData404ResponseModel responseObject = response.as(DictData404ResponseModel.class);

        assertAll(
                () -> assertThat(response.getStatusCode()).isEqualTo(404),
                () -> assertThat(responseObject.getErrorCode()).isEqualTo("NotFoundError"),
                () -> assertThat(responseObject.getErrorData().getId()).isEqualTo(invalidParentCode)
        );
    }
}